/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import classes.Peptido;
import classes.DBManagment.DBManager;
import classes.View.DescripView;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author leisy
 */
public class TareaBasesDeDatos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TareaBasesDeDatos.class.getName());

    /**
     * Creates new form TareaBasesDeDatos
     */
    public TareaBasesDeDatos() {
        initComponents();
        // Suponiendo que tu JLabel se llama 'miLabel'
        Icon  i = peptiditoImage.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(peptiditoImage.getWidth(), peptiditoImage.getHeight(), Image.SCALE_SMOOTH);
        peptiditoImage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        standartSelectionButton = new javax.swing.JRadioButton();
        enterButton = new javax.swing.JButton();
        tittleText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        curatorSelectionButton = new javax.swing.JRadioButton();
        peptiditoImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de Datos de Peptidos");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(231, 212, 187));

        loginButtonGroup.add(standartSelectionButton);
        standartSelectionButton.setForeground(new java.awt.Color(41, 40, 30));
        standartSelectionButton.setText("Consultor");

        enterButton.setBackground(new java.awt.Color(133, 120, 97));
        enterButton.setFont(new java.awt.Font("Consolas", 0, 28)); // NOI18N
        enterButton.setForeground(new java.awt.Color(41, 40, 30));
        enterButton.setText("Enter");
        enterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterButtonMouseClicked(evt);
            }
        });
        enterButton.addActionListener(this::enterButtonActionPerformed);

        tittleText.setFont(new java.awt.Font("Consolas", 2, 30)); // NOI18N
        tittleText.setForeground(new java.awt.Color(41, 40, 30));
        tittleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleText.setText("Base de Datos de Péptidos");
        tittleText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 18, 17));
        jLabel1.setText("Programado por Dora Rodríguez Galpert y José Angel Machado Nieto");

        loginButtonGroup.add(curatorSelectionButton);
        curatorSelectionButton.setForeground(new java.awt.Color(41, 40, 30));
        curatorSelectionButton.setSelected(true);
        curatorSelectionButton.setText("Curador");
        curatorSelectionButton.addActionListener(this::curatorSelectionButtonActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tittleText, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(standartSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(curatorSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tittleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standartSelectionButton)
                    .addComponent(curatorSelectionButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
        );

        peptiditoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peptidito.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peptiditoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(peptiditoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void curatorSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curatorSelectionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curatorSelectionButtonActionPerformed

    private void enterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enterButtonMouseClicked

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        String user = (standartSelectionButton.isSelected())? "consultor" : "curador";
        DescripView dv = new DescripView(user, pepList);
        dv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        pepList = new ArrayList<>();
        DBManager dbMan = new DBManager();
        dbMan.FillPepArray(pepList);
        
//        for(int i=0; i<pepList.size()*(0.05); i++){
//            System.out.println(pepList.get(i).nombre_principal + " -> " + pepList.get(i).organismo_fuente);
//        }
        
        java.awt.EventQueue.invokeLater(() -> new TareaBasesDeDatos().setVisible(true));
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton curatorSelectionButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup loginButtonGroup;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel peptiditoImage;
    private javax.swing.JRadioButton standartSelectionButton;
    private javax.swing.JLabel tittleText;
    // End of variables declaration//GEN-END:variables
    private static ArrayList<Peptido> pepList;
}
