/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package classes.View;

import classes.Peptido;
import classes.DBManagment.DBManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author leisy
 */
public class AddPeptidoDialog extends javax.swing.JDialog {
    
    private ArrayList<String> states = new ArrayList<>();
    private DBManager dbMan = new DBManager();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddPeptidoDialog.class.getName());

    /**
     * Creates new form AddPeptidoDialog
     * @param parent
     * @param modal
     */
    public AddPeptidoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList<String> felipe = dbMan.pullOrganismoFuente();
        
        
        states.add("curado_literatura");
        states.add("validado_espectrometria");
        states.add("predicho");
        states.add("sintetico");
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(felipe.toArray(new String[0]));
        organismoComboBox.setModel(model);
        model = new DefaultComboBoxModel<>(states.toArray(new String[0]));
        stateComboBox.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        nameTextFieldLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        secuenciaTextFieldLabel = new javax.swing.JLabel();
        secuenciaTextField = new javax.swing.JTextField();
        pesoTextFieldLabel = new javax.swing.JLabel();
        pesoTextField = new javax.swing.JTextField();
        cargaTextFieldLabel = new javax.swing.JLabel();
        cargaTextField = new javax.swing.JTextField();
        hidrofobicidadTextFieldLabel = new javax.swing.JLabel();
        hidrofobicidadTextField = new javax.swing.JTextField();
        naturalCheckBox = new javax.swing.JCheckBox();
        stateComboBoxLabel = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<>();
        organismoComboBoxLabel = new javax.swing.JLabel();
        organismoComboBox = new javax.swing.JComboBox<>();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar un nuevo Peptido");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(231, 212, 187));
        jPanel1.setForeground(new java.awt.Color(16, 18, 17));

        tittleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tittleLabel.setText("Introduzca la informacion del nuevo peptido");

        nameTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextFieldLabel.setForeground(new java.awt.Color(41, 40, 30));
        nameTextFieldLabel.setText("Nombre:");

        nameTextField.setBackground(new java.awt.Color(220, 197, 166));
        nameTextField.setForeground(new java.awt.Color(41, 40, 30));
        nameTextField.setText("Nombre del peptido");
        nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextFieldMouseClicked(evt);
            }
        });
        nameTextField.addActionListener(this::nameTextFieldActionPerformed);

        secuenciaTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secuenciaTextFieldLabel.setForeground(new java.awt.Color(41, 40, 30));
        secuenciaTextFieldLabel.setText("Secuencia:");

        secuenciaTextField.setBackground(new java.awt.Color(220, 197, 166));
        secuenciaTextField.setForeground(new java.awt.Color(41, 40, 30));
        secuenciaTextField.setText("Secuencia Peptidica");
        secuenciaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secuenciaTextFieldMouseClicked(evt);
            }
        });
        secuenciaTextField.addActionListener(this::secuenciaTextFieldActionPerformed);

        pesoTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pesoTextFieldLabel.setForeground(new java.awt.Color(41, 40, 30));
        pesoTextFieldLabel.setText("Peso:");

        pesoTextField.setBackground(new java.awt.Color(220, 197, 166));
        pesoTextField.setForeground(new java.awt.Color(41, 40, 30));
        pesoTextField.setText("Peso Molecular");
        pesoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesoTextFieldMouseClicked(evt);
            }
        });
        pesoTextField.addActionListener(this::pesoTextFieldActionPerformed);

        cargaTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cargaTextFieldLabel.setForeground(new java.awt.Color(41, 40, 30));
        cargaTextFieldLabel.setText("Carga:");

        cargaTextField.setBackground(new java.awt.Color(220, 197, 166));
        cargaTextField.setForeground(new java.awt.Color(41, 40, 30));
        cargaTextField.setText("Carga Neta");
        cargaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargaTextFieldMouseClicked(evt);
            }
        });
        cargaTextField.addActionListener(this::cargaTextFieldActionPerformed);

        hidrofobicidadTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hidrofobicidadTextFieldLabel.setForeground(new java.awt.Color(41, 40, 30));
        hidrofobicidadTextFieldLabel.setText("Hidrofobicidad");

        hidrofobicidadTextField.setBackground(new java.awt.Color(220, 197, 166));
        hidrofobicidadTextField.setForeground(new java.awt.Color(41, 40, 30));
        hidrofobicidadTextField.setText("Coeficiente de Hidrofobicidad");
        hidrofobicidadTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidrofobicidadTextFieldMouseClicked(evt);
            }
        });
        hidrofobicidadTextField.addActionListener(this::hidrofobicidadTextFieldActionPerformed);

        naturalCheckBox.setBackground(new java.awt.Color(220, 197, 166));
        naturalCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        naturalCheckBox.setForeground(new java.awt.Color(41, 40, 30));
        naturalCheckBox.setText("Es Natural");
        naturalCheckBox.addActionListener(this::naturalCheckBoxActionPerformed);

        stateComboBoxLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stateComboBoxLabel.setForeground(new java.awt.Color(41, 40, 30));
        stateComboBoxLabel.setText("Estado de Verificacion");

        stateComboBox.setBackground(new java.awt.Color(220, 197, 166));
        stateComboBox.setForeground(new java.awt.Color(41, 40, 30));
        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "curado_literatura", "validado_espectrometria", "predicho", "sintetico" }));

        organismoComboBoxLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        organismoComboBoxLabel.setForeground(new java.awt.Color(41, 40, 30));
        organismoComboBoxLabel.setText("Organismo Fuente");

        organismoComboBox.setBackground(new java.awt.Color(220, 197, 166));
        organismoComboBox.setForeground(new java.awt.Color(41, 40, 30));
        organismoComboBox.addActionListener(this::organismoComboBoxActionPerformed);

        confirmButton.setBackground(new java.awt.Color(220, 197, 166));
        confirmButton.setForeground(new java.awt.Color(41, 40, 30));
        confirmButton.setText("Confirmar");
        confirmButton.addActionListener(this::confirmButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naturalCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(organismoComboBoxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(organismoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(stateComboBoxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hidrofobicidadTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hidrofobicidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cargaTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pesoTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(secuenciaTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(secuenciaTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(nameTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(tittleLabel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secuenciaTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secuenciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargaTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hidrofobicidadTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hidrofobicidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naturalCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateComboBoxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organismoComboBoxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(organismoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmButton)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hidrofobicidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidrofobicidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hidrofobicidadTextFieldActionPerformed

    private void cargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaTextFieldActionPerformed

    private void pesoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTextFieldActionPerformed

    private void secuenciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secuenciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secuenciaTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextFieldMouseClicked
        if("Nombre del peptido".equals(nameTextField.getText())){
            nameTextField.setText("");
        }
    }//GEN-LAST:event_nameTextFieldMouseClicked

    private void secuenciaTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secuenciaTextFieldMouseClicked
        if("Secuencia Peptidica".equals(secuenciaTextField.getText())){
            secuenciaTextField.setText("");
        }
    }//GEN-LAST:event_secuenciaTextFieldMouseClicked

    private void pesoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesoTextFieldMouseClicked
        if("Peso Molecular".equals(pesoTextField.getText())){
            pesoTextField.setText("");
        }
    }//GEN-LAST:event_pesoTextFieldMouseClicked

    private void cargaTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargaTextFieldMouseClicked
        if("Carga Neta".equals(cargaTextField.getText())){
            cargaTextField.setText("");
        }
    }//GEN-LAST:event_cargaTextFieldMouseClicked

    private void hidrofobicidadTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidrofobicidadTextFieldMouseClicked
        if("Coeficiente de Hidrofobicidad".equals(hidrofobicidadTextField.getText())){
            hidrofobicidadTextField.setText("");
        }
    }//GEN-LAST:event_hidrofobicidadTextFieldMouseClicked

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        Peptido newPep = new Peptido(secuenciaTextField.getText(),
            nameTextField.getText(),
            Double.parseDouble(pesoTextField.getText()),
            Integer.parseInt(cargaTextField.getText()),
            Double.parseDouble(hidrofobicidadTextField.getText()),
            naturalCheckBox.isSelected(),
            states.get(stateComboBox.getSelectedIndex()),
            (organismoComboBox.getSelectedIndex()+1) + ""
        );
        try {
            dbMan.ExecuteInsertQuery(newPep);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void organismoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organismoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organismoComboBoxActionPerformed

    private void naturalCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naturalCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naturalCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddPeptidoDialog dialog = new AddPeptidoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cargaTextField;
    private javax.swing.JLabel cargaTextFieldLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField hidrofobicidadTextField;
    private javax.swing.JLabel hidrofobicidadTextFieldLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nameTextFieldLabel;
    private javax.swing.JCheckBox naturalCheckBox;
    private javax.swing.JComboBox<String> organismoComboBox;
    private javax.swing.JLabel organismoComboBoxLabel;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JLabel pesoTextFieldLabel;
    private javax.swing.JTextField secuenciaTextField;
    private javax.swing.JLabel secuenciaTextFieldLabel;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateComboBoxLabel;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}
